import { randomUUID } from 'node:crypto';
import { estimateCostUsd } from '@obs/shared';
import { closeDb, getDb } from './index.js';
import { runMigrations } from './migrate.js';

// npm run seed
const PROVIDERS = [
  { provider: 'gemini', model: 'gemini-2.5-flash', weight: 6 },
  { provider: 'groq', model: 'llama-3.3-70b-versatile', weight: 3 },
  { provider: 'hf', model: 'Qwen/Qwen2.5-7B-Instruct', weight: 1 },
];

const TITLES = [
  'Explain how vector databases work',
  'Debug a failing CI pipeline',
  'Summarise the quarterly metrics',
  'Write a SQL migration for a new table',
  'Plan a zero-downtime Kubernetes rollout',
  'Draft release notes for v2.0',
];

const ERROR_TYPES = ['RateLimitError', 'ProviderError', 'TimeoutError'];

const WINDOW_MIN = 55;
const LOG_COUNT = 160;

const rand = (min: number, max: number): number => min + Math.random() * (max - min);
const pick = <T>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)]!;

function pickProvider() {
  const total = PROVIDERS.reduce((s, p) => s + p.weight, 0);
  let r = Math.random() * total;
  for (const p of PROVIDERS) {
    r -= p.weight;
    if (r <= 0) return p;
  }
  return PROVIDERS[0]!;
}

async function seed(): Promise<void> {
  await runMigrations();
  const db = getDb();

  await db.deleteFrom('inference_logs').execute();
  await db.deleteFrom('messages').execute();
  await db.deleteFrom('conversations').execute();
  await db.deleteFrom('raw_events').execute();

  const now = Date.now();
  const iso = (msAgo: number): string => new Date(now - msAgo).toISOString();

  const conversationIds: string[] = [];
  for (let i = 0; i < TITLES.length; i++) {
    const id = randomUUID();
    conversationIds.push(id);
    const createdAgo = rand(WINDOW_MIN, 5) * 60_000;
    const status = i === 4 ? 'cancelled' : i === 5 ? 'archived' : 'active';
    const turns = Math.floor(rand(2, 5)) * 2;

    await db
      .insertInto('conversations')
      .values({
        id,
        title: TITLES[i]!,
        status,
        provider: 'gemini',
        model: 'gemini-2.5-flash',
        message_count: turns,
        created_at: iso(createdAgo),
        updated_at: iso(createdAgo - rand(0, 4) * 60_000),
      })
      .execute();

    for (let s = 0; s < turns; s++) {
      await db
        .insertInto('messages')
        .values({
          id: randomUUID(),
          conversation_id: id,
          role: s % 2 === 0 ? 'user' : 'assistant',
          content:
            s % 2 === 0
              ? `Demo user message ${s / 2 + 1} for "${TITLES[i]}".`
              : 'Demo assistant reply generated by the seed script.',
          sequence: s,
          token_count: Math.floor(rand(20, 220)),
          redacted: 0,
          inference_event_id: null,
          created_at: iso(createdAgo - s * 20_000),
        })
        .execute();
    }
  }

  let errors = 0;
  for (let i = 0; i < LOG_COUNT; i++) {
    const { provider, model } = pickProvider();
    const conversationId = pick(conversationIds);
    const isError = Math.random() < 0.06;
    if (isError) errors += 1;

    const latency = Math.round(rand(180, 850) + (Math.random() < 0.15 ? rand(0, 2600) : 0));
    const promptTokens = isError ? null : Math.floor(rand(25, 420));
    const completionTokens = isError ? null : Math.floor(rand(15, 300));
    const totalTokens =
      promptTokens !== null && completionTokens !== null ? promptTokens + completionTokens : null;
    const usage =
      promptTokens !== null && completionTokens !== null
        ? { promptTokens, completionTokens, totalTokens: totalTokens! }
        : undefined;
    const createdAgo = rand(0, WINDOW_MIN) * 60_000;

    await db
      .insertInto('inference_logs')
      .values({
        id: randomUUID(),
        event_id: randomUUID(),
        conversation_id: conversationId,
        message_id: null,
        session_id: `seed-session-${i % 12}`,
        provider,
        model,
        status: isError ? 'error' : 'success',
        streaming: Math.random() < 0.7 ? 1 : 0,
        latency_ms: latency,
        ttft_ms: isError ? null : Math.round(latency * rand(0.3, 0.6)),
        prompt_tokens: promptTokens,
        completion_tokens: completionTokens,
        total_tokens: totalTokens,
        finish_reason: isError ? null : 'stop',
        error_type: isError ? pick(ERROR_TYPES) : null,
        error_message: isError ? 'Simulated provider failure (seed data)' : null,
        input_preview: 'Demo prompt preview generated by the seed script.',
        output_preview: isError ? '' : 'Demo response preview generated by the seed script.',
        estimated_cost_usd: estimateCostUsd(model, usage),
        pii_redaction_count: 0,
        extra: '{"seed":true}',
        request_timestamp: iso(createdAgo + latency),
        response_timestamp: iso(createdAgo),
        created_at: iso(createdAgo),
      })
      .execute();
  }

  process.stdout.write(
    `[seed] inserted ${conversationIds.length} conversations and ${LOG_COUNT} inference logs ` +
      `(${errors} errors) across the last ${WINDOW_MIN} minutes.\n`,
  );
  process.stdout.write('[seed] open the dashboard to see populated latency / throughput / error charts.\n');
  await closeDb();
}

seed().catch((err) => {
  process.stderr.write(`[seed] failed: ${err instanceof Error ? err.stack ?? err.message : String(err)}\n`);
  process.exitCode = 1;
});
